---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ehr.
--- DateTime: 2019/10/12 13:44
---

local luasnow = require("snowflake")

local snowflake = luasnow:new(1, 1)

local start_ts = os.clock()

for i = 1, 1000000, 1 do
    local id = snowflake:get_id()
    if id == nil then
        print("id is nil")
        break
    else
        print(id)
    end
end
local end_ts = os.clock()
print(string.format("100W done, time: %s s", end_ts - start_ts))





